### PR TITLE
Add Makefile targets to improve the dev install experience

### PR DESCRIPTION
**Pull request by BradGriffith**
This is still in Draft state because I'll want to update the README after PR2 is merged.

With these new targets in place, the dev install experience should be smoother--particularly with nginx-proxy and the missing `composer install` step.

### CODE REVIEW

**Comment by hawkinsw** [comment]
This is excellent. I pulled and worked through it. Much, much improved. Good data was loaded. Maps are aligned on Ohio. nginx-proxy easily up/down with Makefile support. Really like the env.mk.example. I see nothing to change. I'll be happy to work on the README.md once you believe that this draft is in a good state and we have merged in the previous PR. 

Thanks again for letting me help!
Will

**Comment by BradGriffith** [comment]
Thanks for helping me work through this, @hawkinsw ! Could you take a look and see how this branch/PR works for you?

**Comment by mikestratton** [comment]
Most laravel apps do not use Docker as part of the install process, just an FYI.

**Comment by mikestratton** [comment]
Just an FYI, most Laravel devs install any laravel app in 6 steps, give or take a few:
1. git clone
2. composer install
3. touch .env
4. php artisan key:generate
5. php artisan migrate
6. php artisan db:seed

**Comment by BradGriffith** [comment]
@mikestratton Thanks for the input on this. It's a good conversation to have as we figure out how to collaborate effectively as a team of volunteer developers.

It may very well be accurate that a majority of Laravel developers use something other than Docker. The method you listed would actually work fine for anyone who wants to go that route with this repo. You would just need to `cd src` before running commands 2-6. But those commands you listed don't start up a web server, so there's still got to be another step such as running `php artisan serve` or using Homestead or configuring XAMPP or MAMP.

I've found docker-compose to be a highly repeatable method for keeping development environments consistent across a team of developers, particularly when we may each be using a different OS. This setup with docker-compose also enables us to run Laravel, Mailhog (email trap/catcher for dev environments), pgadmin (UI for Postgres) all on port 80 with different hostnames. That usually takes some configuration under other setups like Homestead or XAMPP.

But at the end of the day, I want to make sure this is flexible for everyone. Feel free to use this the way you typically would, pointing your preferred web server Document Root to the vaccinateoh/src directory, and you can use it with the commands you listed above. As a reference, the environment variables in my setup are in the `build/env.mk.example` file including a google maps key variable that gets injected into Mix for clientside use.

And again, I encourage this sort of exchange. I definitely like to know what makes it easier or harder for developers to onboard so that we can benefit from everyone's contributions!

**Comment by BradGriffith** [comment]
@hawkinsw I think I'll leave this PR for you to merge so that I'm not merging my own. Let me know if you have suggestions or changes before merging!

**Comment by hawkinsw** [comment]
Will merge ASAP. I agree that not merging an "own" PR is a good idea!

**Comment by hawkinsw** [comment]
Sending back to @BradGriffith for review of this latest push. :-)

**Comment by BradGriffith** [comment]
Looks good--I like your improvements! I figure we've gone back and forth enough times that I won't send it back to you just to merge. Thanks for your help with this.

**Pull request merged**
